set(_CATKIN_CURRENT_PACKAGE "ackermann_encoder_odometry")
set(ackermann_encoder_odometry_VERSION "0.0.1")
set(ackermann_encoder_odometry_MAINTAINER "Your Name <your@email.com>")
set(ackermann_encoder_odometry_PACKAGE_FORMAT "2")
set(ackermann_encoder_odometry_BUILD_DEPENDS "roscpp" "nav_msgs" "tf" "serial" "message_generation")
set(ackermann_encoder_odometry_BUILD_EXPORT_DEPENDS )
set(ackermann_encoder_odometry_BUILDTOOL_DEPENDS "catkin")
set(ackermann_encoder_odometry_BUILDTOOL_EXPORT_DEPENDS )
set(ackermann_encoder_odometry_EXEC_DEPENDS "roscpp" "nav_msgs" "tf" "serial" "message_runtime")
set(ackermann_encoder_odometry_RUN_DEPENDS "roscpp" "nav_msgs" "tf" "serial" "message_runtime")
set(ackermann_encoder_odometry_TEST_DEPENDS )
set(ackermann_encoder_odometry_DOC_DEPENDS )
set(ackermann_encoder_odometry_URL_WEBSITE "")
set(ackermann_encoder_odometry_URL_BUGTRACKER "")
set(ackermann_encoder_odometry_URL_REPOSITORY "")
set(ackermann_encoder_odometry_DEPRECATED "")