obstacle_range: 5.0
raytrace_range: 6.0
inflation_radius: 0.6
transform_tolerance: 1

observation_sources: laser_scan
laser_scan:
 sensor_frame: laser
 data_type: LaserScan
 topic: scan
 marking: true
 clearing: true
